name: Java CI with Maven

on:
  push: ~
  pull_request:
    branches: [ master, main, production ]

jobs:
  my_task:
    runs-on: ubuntu-latest
    steps:
      - name: "lets do something"
        run: "echo 'hello world'"
        
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B test
